### ISSUE TITLE
Provide nuget package

### ISSUE THREAD

**Issue by MagicAndre1981** [jedusei/AndroidX.Core.SplashScreen#1]
Can you please provide a nuget package?

**Comment by MagicAndre1981** [comment]
there is also a newer beta version of the jar:

https://developer.android.com/jetpack/androidx/releases/core#core-splashscreen-1.0.0-beta01
https://dl.google.com/android/maven2/androidx/core/core-splashscreen/1.0.0-beta01/core-splashscreen-1.0.0-beta01.aar

**Comment by jedusei** [comment]
Hi @MagicAndre1981,

I don't want to upload this to Nuget because it's just meant to be a temporary placeholder for the official binding which is yet to be released. According to [this](https://github.com/xamarin/AndroidX/issues/455#issuecomment-1069451338), the official binding package will be created only after a stable version of the jar is released. So for now you'll have to clone the project and replace the jar with the newer beta version.

**Comment by MagicAndre1981** [comment]
ok, I created a nuget, added it to my project, but SplashScreen.InstallSplashScreen is not found and `using AndroidX.Core.SplashScreen;` shows an error. Looks like I'll have to wait for the official version
